# Generated by Django 6.1.1 on 2026-09-27 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('common_name', models.CharField(max_length=120)),
                ('scientific_name', models.CharField(max_length=160)),
                ('short_blurb', models.TextField()),
                ('note', models.TextField(blank=True)),
                ('map_x', models.FloatField()),
                ('map_y', models.FloatField()),
                ('glow', models.CharField(default='#3d9e8f', max_length=20)),
                ('shared_genes', models.JSONField(default=list)),
                ('unique_genes', models.JSONField(default=list)),
                ('genome_source', models.CharField(blank=True, default='mock', max_length=80)),
                ('is_public_genome', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['common_name'],
            },
        ),
    ]
