from django.core.management.base import BaseCommand
from organisms.models import Organism

# Core seeded organisms — map positions spread across a large field.
# Procedural nodes fill edges as the camera pans/zooms (frontend).
SEED = [
    {
        "slug": "bakers-yeast",
        "common_name": "Baker's yeast",
        "scientific_name": "Saccharomyces cerevisiae",
        "short_blurb": "The classic lab fungus. A compact genome where gene → trait stories are unusually readable.",
        "note": "",
        "map_x": 0,
        "map_y": 0,
        "glow": "#3d9e8f",
        "shared_genes": ["ACT1", "EF1A", "TUB1"],
        "unique_genes": ["HO", "SUC2"],
        "genome_source": "mock-public",
    },
    {
        "slug": "oyster-mushroom",
        "common_name": "Oyster mushroom",
        "scientific_name": "Pleurotus ostreatus",
        "short_blurb": "A wood-decay basidiomycete. Hyphal networks and fruiting bodies make structure visible at human scale.",
        "note": "",
        "map_x": 420,
        "map_y": -180,
        "glow": "#2a8f82",
        "shared_genes": ["ACT1", "EF1A", "LAC1"],
        "unique_genes": ["POX1", "VEL1"],
        "genome_source": "mock-public",
    },
    {
        "slug": "psilocybe-cubensis-annotation",
        "common_name": "Psilocybe (public genome)",
        "scientific_name": "Psilocybe cubensis (annotation)",
        "short_blurb": "Public sequence annotation of a medicinal/psilocybe-type genome. Explore shared fungal architecture — not cultivation.",
        "note": "Data is public sequence annotation only. No cultivation content.",
        "map_x": -380,
        "map_y": 260,
        "glow": "#c4784a",
        "shared_genes": ["ACT1", "EF1A", "PSI"],
        "unique_genes": ["PSI_CLUSTER_STUB"],
        "genome_source": "mock-public-annotation",
    },
    {
        "slug": "neurospora",
        "common_name": "Bread mold",
        "scientific_name": "Neurospora crassa",
        "short_blurb": "A genetic workhorse for circadian rhythms and gene silencing. Threads of regulation made measurable.",
        "note": "",
        "map_x": 200,
        "map_y": 340,
        "glow": "#3d9e8f",
        "shared_genes": ["ACT1", "EF1A", "WC1"],
        "unique_genes": ["FRQ", "WC2"],
        "genome_source": "mock-public",
    },
    {
        "slug": "aspergillus-nidulans",
        "common_name": "A. nidulans",
        "scientific_name": "Aspergillus nidulans",
        "short_blurb": "Model ascomycete for secondary metabolism and developmental genetics.",
        "note": "",
        "map_x": -520,
        "map_y": -120,
        "glow": "#2f8a7c",
        "shared_genes": ["ACT1", "EF1A", "VEA"],
        "unique_genes": ["BRLE", "ABAB"],
        "genome_source": "mock-public",
    },
    {
        "slug": "schizosaccharomyces",
        "common_name": "Fission yeast",
        "scientific_name": "Schizosaccharomyces pombe",
        "short_blurb": "Cell-cycle genetics in a yeast that divides by fission — a different silhouette of the same story.",
        "note": "",
        "map_x": 120,
        "map_y": -420,
        "glow": "#3d9e8f",
        "shared_genes": ["ACT1", "EF1A", "CDC2"],
        "unique_genes": ["STE11"],
        "genome_source": "mock-public",
    },
    {
        "slug": "candida-albicans",
        "common_name": "C. albicans",
        "scientific_name": "Candida albicans",
        "short_blurb": "Dimorphic yeast; morphology switches illuminate how genotype meets environment.",
        "note": "Research / public-genome framing only.",
        "map_x": -200,
        "map_y": -300,
        "glow": "#358f82",
        "shared_genes": ["ACT1", "EF1A", "HWP1"],
        "unique_genes": ["EFG1"],
        "genome_source": "mock-public",
    },
    {
        "slug": "cryptococcus",
        "common_name": "Cryptococcus",
        "scientific_name": "Cryptococcus neoformans",
        "short_blurb": "Basidiomycete yeast with a well-mapped virulence and mating genetics literature.",
        "note": "Public annotation focus.",
        "map_x": 560,
        "map_y": 200,
        "glow": "#2a8f82",
        "shared_genes": ["ACT1", "EF1A", "CAP59"],
        "unique_genes": ["STE12a"],
        "genome_source": "mock-public",
    },
    {
        "slug": "ustilago",
        "common_name": "Corn smut",
        "scientific_name": "Ustilago maydis",
        "short_blurb": "A plant-associated basidiomycete whose mating-type loci are textbook genetics.",
        "note": "",
        "map_x": -100,
        "map_y": 480,
        "glow": "#3d9e8f",
        "shared_genes": ["ACT1", "EF1A", "B_LOCUS"],
        "unique_genes": ["PRA1"],
        "genome_source": "mock-public",
    },
    {
        "slug": "coprinopsis",
        "common_name": "Ink cap model",
        "scientific_name": "Coprinopsis cinerea",
        "short_blurb": "Mushroom development genetics — fruiting as a readout of developmental programs.",
        "note": "",
        "map_x": 680,
        "map_y": -80,
        "glow": "#2f8a7c",
        "shared_genes": ["ACT1", "EF1A", "DST1"],
        "unique_genes": ["CC1"],
        "genome_source": "mock-public",
    },
    {
        "slug": "magnaporthe",
        "common_name": "Rice blast fungus",
        "scientific_name": "Magnaporthe oryzae",
        "short_blurb": "Plant-pathogen genetics with clear morphological infection structures in the literature.",
        "note": "Public genome / research framing.",
        "map_x": -640,
        "map_y": 140,
        "glow": "#358f82",
        "shared_genes": ["ACT1", "EF1A", "PMK1"],
        "unique_genes": ["MPG1"],
        "genome_source": "mock-public",
    },
    {
        "slug": "trichoderma",
        "common_name": "Trichoderma",
        "scientific_name": "Trichoderma reesei",
        "short_blurb": "Industrial cellulase genetics — enzymes as the visible tip of a regulatory network.",
        "note": "",
        "map_x": 320,
        "map_y": 520,
        "glow": "#3d9e8f",
        "shared_genes": ["ACT1", "EF1A", "XYR1"],
        "unique_genes": ["CBH1"],
        "genome_source": "mock-public",
    },
]


class Command(BaseCommand):
    help = "Seed mock fungal organisms for the Hyphaneural map"

    def handle(self, *args, **options):
        n = 0
        for row in SEED:
            Organism.objects.update_or_create(slug=row["slug"], defaults=row)
            n += 1
        self.stdout.write(self.style.SUCCESS(f"Seeded {n} organisms"))
